### ISSUE TITLE
Recent updates?

### ISSUE THREAD

**Issue by eightheads** [FrankenVoron/FT-V#1]
Any recent updates or changes to this project? Planning to start converting my FT-5 sometime soon and would like to work off the most up-to-date changes, thanks!

**Comment by eddietheengineer** [comment]
Hey! This repo is pretty out of date right now, but most of the Voron V1.8 CAD will work for the gantry assuming you are willing to buy MGN9 rails 👍🏼 . The Z upgrades/assembly will be getting an update later this year that should be good.

**Comment by eightheads** [comment]
Thanks man!
