### ISSUE TITLE
Could CAD files be made available?

### ISSUE THREAD

**Issue by tetious** [FrankenVoron/FT-V#2]
I'm looking to make various tweaks to this design, and creating an assembly to get an overall picture in my CAD tool of choice requires solid bodies instead of meshes: STLs won't do. While I could build them using the STLs as reference, that is fairly involved and annoying. 

Starting from a step file is so much easier, and from the picture in the root readme, I suspect these existed at some point. :) Do you happen to have step files for the various parts you customized sitting around somewhere that you could add?

I totally understand if they are misplaced or recent work has left them no longer available, making this impossible. Just thought I'd ask!

Thanks for all your awesome work on this project. The documentation and BOMs in particular are brilliant!

**Comment by itsthejoker** [comment]
This is a question for @eddietheengineer -- I believe he has the source, but I'm not sure what the stance is on publishing them.

**Comment by eddietheengineer** [comment]
@tetious believe it or not--the FT-V was done entirely from STLs because that's all that Voron released at the time! So I don't have any native CAD STEP file--only the STLs. 

I do plan on doing an update to this later in the year--at that point there would be a full CAD assembly that is based on the Voron V1 :)

**Comment by tetious** [comment]
@eddietheengineer oh wow. Well, this makes me even more grateful for all your hard work!

I was delighted to see this project as I've always been fond of my FT-5, mostly because it was my first "major" build, when I was just getting started in this. Ahh, nostalgia. As you mention, it had various problems and never performed all that well. It feels great to give it new life. 

I'm excited to see the updates you have planned! I'm also excited to get started, so I'm going to tinker with this version and will surely upgrade later. For the moment, my tweaks will be focused on the x carriage and toolhead. Gonna do a DD mount for a Sherpa Mini + v6. Should be fun! 

Thanks for the quick response! Let me know how I can help with your future plans!
